package com.example.demo.model;

public enum Area {
	ANDHERI_WEST, ANDHERI_EAST, BANDRA_WEST, BANDRA_EAST, BORIVALI_WEST, BORIVALI_EAST, CHEMBUR, DAHISAR, DADAR_WEST,
	DADAR_EAST, GOREGAON_WEST, GOREGAON_EAST, KANDIVALI_WEST, KANDIVALI_EAST, KURLA, LOWER_PAREL, MALAD_WEST,
	MALAD_EAST, MULUND_WEST, MULUND_EAST, VILE_PARLE_WEST, VILE_PARLE_EAST, ANDHERI, WORLI, KALINA, MAHIM,
	MUMBAI_CENTRAL, MUMBAI_SOUTH, MUMBAI_EAST, MUMBAI_WEST, VERSOVA, KOPAR_KHAIRNE, NAVI_MUMBAI, SEAWOODS, PANVEL,
	VASHI, BELAPUR, GHATKOPAR_EAST, GHATKOPAR_WEST, SANTACRUZ_WEST, SANTACRUZ_EAST, MIRA_BHAYANDAR, NALASOPARA, VIRAR
}
