package com.example.demo.model;

public enum Town {
	PANVEL, VASHI, BELAPUR, KALYAN, ULHASNAGAR, DOMBIVLI, VIRAR, MIRA_BHAYANDAR, NALASOPARA,
	KOPAR_KHAIRNE, SEAWOODS, THANE, MUMBRA, AMBARNATH, BADLAPUR, BHAYANDAR, KANDIVALI, BORIVALI, KALYAN_DOMBIVLI,
	PALGHAR, BHIWANDI

}
